// packages/vue-todo/src/App.vue
<template>
  <div style="margin: 20px">
    <h1>Vue Todo</h1>
    <input v-model="newTodo" placeholder="Add a todo" />
    <button @click="addTodo">Add</button>
    <ul>
      <li v-for="(todo, index) in todos" :key="index">
        {{ todo }}
        <button @click="removeTodo(index)">X</button>
      </li>
    </ul>
  </div>
</template>

<script>
import { ref } from "vue";

export default {
  setup() {
    const todos = ref([]);
    const newTodo = ref("");

    function addTodo() {
      if (!newTodo.value.trim()) return;
      todos.value.push(newTodo.value);
      newTodo.value = "";
    }

    function removeTodo(index) {
      todos.value.splice(index, 1);
    }

    return { todos, newTodo, addTodo, removeTodo };
  },
};
</script>

// packages/angular-todo/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterOutlet } from "@angular/router";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";

@Component({
  selector: "app-root",
  imports: [RouterOutlet, CommonModule, FormsModule],
  template: `
    <div style="margin: 20px;">
      <h1>Angular Todo</h1>
      <input [(ngModel)]="newTodo" placeholder="Add a todo" />
      <button (click)="addTodo()">Add</button>
      <ul>
        <li *ngFor="let todo of todos; let i = index">
          {{ todo }}
          <button (click)="removeTodo(i)">X</button>
        </li>
      </ul>
    </div>

    <router-outlet />
  `,
  styles: [],
})
export class AppComponent {
  newTodo = "";
  todos: string[] = [];

  addTodo() {
    if (this.newTodo.trim()) {
      this.todos.push(this.newTodo);
      this.newTodo = "";
    }
  }

  removeTodo(index: number) {
    this.todos.splice(index, 1);
  }
}
